[features]
seeds = false
skip-lint = false

[programs.localnet]
cp_amm = "9sh3gorJVsWgpdJo317PqnoWoTuDN2LkxiyYUUTu4sNJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keys/local/admin-bossj3JvwiNK7pvjr149DqdtJxf2gdygbcmEPTkb2F1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.0"
